export const SUPABASE_URL = 'https://jgmoztmjpsuysrbuqokv.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbW96dG1qcHN1eXNyYnVxb2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNzU5MDAsImV4cCI6MjA3ODY1MTkwMH0.IcufpzAcrRbmRcQbtpthdUvAMNa4PUB-RtM2f0l-UU8';
